{% set name = "chalice" %}
{% set version = "1.21.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b7a17583e0553caa0e44d23186b4aad069f7665c24a473104d1f04e62cc4cb07

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py2k or win]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pip >=9,<20.1
    - click >=7,<8.0
    - botocore >=1.12.86,<2.0.0
    - typing ==3.6.4  # [py<37]
    - mypy_extensions
    - six >=1.10.0,<2.0.0
    - attrs >=19.3.0,<20.3.0
    - enum-compat >=0.0.2
    - jmespath >=0.9.3,<1.0.0
    - pyyaml >=5.3.1,<6.0.0
    - wheel
  run_constrained:
    - watchdog ==0.8.3

test:
  requires:
    - pip
  imports:
    - chalice
    - chalice.cli
    - chalice.cli.filewatch
    - chalice.deploy
  commands:
    - pip check
    - chalice --help

about:
  home: https://github.com/aws/chalice
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Chalice is a microframework for writing serverless apps in python.

  description: |
    Chalice is a microframework for writing serverless apps in python. It allows you to quickly create and deploy applications that use AWS Lambda. It provides:
      - A command line tool for creating, deploying, and managing your app
      - A decorator based API for integrating with Amazon API Gateway, Amazon S3, Amazon SNS, Amazon SQS, and other AWS services.
      - Automatic IAM policy generation
  doc_url: http://chalice.readthedocs.io/en/latest/
  dev_url: https://github.com/aws/chalice

extra:
  recipe-maintainers:
    - sodre
