{% set name = "chalice" %}
{% set version = "1.29.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f07aad9a2d4e5b06ef279cf668a48ec455b131168000b91efe7d841425599035

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py2k or win]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pip >=9,<21.4
    - click >=7,<9.0
    - botocore >=1.14.0,<2.0.0
    - typing ==3.6.4  # [py<37]
    - typing-extensions
    - six >=1.10.0,<2.0.0
    - attrs >=19.3.0,<21.3.0
    - enum34  # [py<34]
    - jmespath >=0.9.3,<1.0.0
    - pyyaml >=5.3.1,<7.0.0
    - inquirer >=2.7.0,<3.0.0
    - wheel
  run_constrained:
    - watchdog ==0.8.3

test:
  requires:
    - pip
  imports:
    - chalice
    - chalice.cli
    - chalice.cli.filewatch
    - chalice.deploy
  commands:
    # TBD: inquirer's setup.py depdends on blessed==1.17.6, but conda package install blessed==1.18.0
    # - pip check
    - chalice --help

about:
  home: https://github.com/aws/chalice
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Chalice is a microframework for writing serverless apps in python.

  description: |
    Chalice is a microframework for writing serverless apps in python. It allows you to quickly create and deploy applications that use AWS Lambda. It provides:
      - A command line tool for creating, deploying, and managing your app
      - A decorator based API for integrating with Amazon API Gateway, Amazon S3, Amazon SNS, Amazon SQS, and other AWS services.
      - Automatic IAM policy generation
  doc_url: http://chalice.readthedocs.io/en/latest/
  dev_url: https://github.com/aws/chalice

extra:
  recipe-maintainers:
    - sodre
    - markllama
    - dgasmith
